obsidian_entrypoint_path_str: './Saludos.md'
obsidian_folder_path_str: '.'
html_output_folder_path_str: './html/'
site_name: El sitio de FROSADO
# Not needed if using custom template
# html_custom_inclusions:
#  - '<link rel="stylesheet" href="/assets/custom.css" />'
#  - '<script src="/assets/custom.js"></script>'
html_template_path_str: 'template.html'
toggles:
  # If this is false only the entrypoint and all its links (recursively) are processed
  # if true all the notes will be processed
  process_all: false
  features:
    folder_notes:
      enabled: True
      placement: 'inside folder'   # 'inside folder' , 'outside folder' 
      naming: 'folder name'
    breadcrumbs:
      enabled: True
    tags_page:
      enabled: True
      styling:
        show_icon: True
        show_in_note_footer: True
    embedded_search:
      enabled: True
    graph:
      enabled: True           # Include code to build the graph view per page (default: True)
      show_inclusions_in_graph: True
      templates:
        - id: 2d
          name: 2d
          path: builtin<2d>
        - id: 3d
          name: 3d
          path: builtin<3d>
      styling:
        show_icon: True
    rss:
      enabled: False
      host_root: 'https://frosado.github.io/'
      styling: 
        show_icon: True
      channel: 
        title: 'El sitio de notas de FROSADO'
        website_link: 'https://frosado.github.io/'
        description: 'El sitio de FROSADO'
        language_code: 'es-ES'
        managing_editor: 'n/a'
        web_master: 'n/a'
      items:
        selector: 
          match_keys: []
          exclude_keys: []
          include_subfolders: []
          exclude_subfolders: ['.git','obs.html']
          exclude_files: ['not_created.html', 'index.html']
        description:
          selectors:
            - ['yaml','rss:description']
            - ['first-paragraphs', 2, '<br/><br/>']
            - ['first-header', 1]
        title: 
          selectors: 
            - ['yaml','rss:title']
            - ['first-header', 1]
            - ['path', ['parent',1], '/ ', ['stem']]
        publish_date: 
          selectors: 
            - ['yaml','rss:publish_date']
            - ['yaml_strip','tags',['date/']]
          iso_formatted: True
          format_string: ''
    table_of_contents:
      add_toc_when_missing: True          # add "[TOC]" (Table of Contents) when missing
    create_index_from_dir_structure:
      enabled: True
      verbose: False
      rel_output_path: 'dirtree.html'
      styling: 
        show_icon: True
      exclude_subfolders:
        - ".git"
        - "resources"
        - "**/snippets"
      exclude_files:
        - ".gitignore"
        - "favicon.ico"
        - "not_created.html"
      homepage_label: "Home"
    